CODE_COUNTRY = {
    "ARG": "Argentina",
    "AUS": "Australia",
    "AUT": "Austria",
    "BEL": "Belgium",
    "BRA": "Brazil",
    "BGR": "Bulgaria",
    "CAN": "Canada",
    "CHN": "China",
    "COL": "Colombia",
    "CUB": "Cuba",
    "CZE": "Czechia",
    "EGY": "Egypt",
    "FRA": "France",
    "DEU": "Germany",
    "GRC": "Greece",
    "HKG": "Hong Kong",
    "HUN": "Hungary",
    "IND": "India",
    "IDN": "Indonesia",
    "IRL": "Ireland",
    "ISR": "Israel",
    "ITA": "Italy",
    "JPN": "Japan",
    "LVA": "Latvia",
    "LTU": "Lithuania",
    "MYS": "Malaysia",
    "MEX": "Mexico",
    "MAR": "Morocco",
    "NLD": "Netherlands",
    "NZL": "New Zealand",
    "NGA": "Nigeria",
    "NOR": "Norway",
    "PHL": "Philippines",
    "POL": "Poland",
    "PRT": "Portugal",
    "ROU": "Romania",
    "RUS": "Russia",
    "SAU": "Saudi Arabia",
    "SRB": "Serbia",
    "SGP": "Singapore",
    "SVK": "Slovakia",
    "SVN": "Slovenia",
    "ZAF": "South Africa",
    "KOR": "Korea, South",
    "SWE": "Sweden",
    "CHE": "Switzerland",
    "TWN": "Taiwan",
    "THA": "Thailand",
    "TUR": "Turkey",
    "ARE": "United Arab Emirates",
    "UKR": "Ukraine",
    "GBR": "United Kingdom",
    "USA": "United States",
    "VEN": "Venezuela"
}
